log_level = "warn,ashell=info,ashell::services::network=debug"
outputs = "All"
position = "Top"

clipboard_cmd = "cliphist | wl-copy"

[modules]
left = [ "SystemInfo", "Temperature" ]
center = [ "Workspaces", "WindowTitle" ]
right = [ "clipboard", "Tray", "Clock", "Privacy", "Settings" ]

[workspaces]
enable_workspace_filling = false

[window_title]
truncate_title_after_length = 100

[settings]
lock_cmd = "playerctl --all-players pause; hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "bluetuith"

[appearance.menu]
opacity = 0.7
backdrop = 0.3

[appearance]

scale_factor = 2.0
opacity = 0.8

primary_color = "#7aa2f7"
success_color = "#9ece6a"
text_color = "#a9b1d6"

workspace_colors = [ "#7aa2f7", "#9ece6a" ]

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#1a1b26"
weak = "#24273a"
strong = "#414868"

[appearance.secondary_color]
base = "#0c0d14"

[system_info.temperature]
warn_threshold = 60
alert_threshold = 80
sensor = "acpitz temp1"
